batch_size: 20
image_size: 224
model_backbone: resnet50
model_dropout_rate: 0.3
model_freeze_backbone: true
model_full_unfreeze_epoch: 5
model_pretrained: true
model_staged_unfreeze_epoch: 4
model_staged_unfreeze_layer: layer4
num_workers: 4
optim_backbone_lr: 3.0e-05
optim_betas: !!python/tuple
- 0.9
- 0.999
optim_cosine_T_0: 5
optim_cosine_T_mult: 2
optim_gamma: 0.5
optim_head_lr: 0.0001
optim_lr: 0.0001
optim_momentum: 0.9
optim_optim: adamw
optim_patience: 2
optim_scheduler: cosine_warm_restart
optim_step_size: 1
optim_weight_decay: 0.0005
train_early_stop_patience: 5
train_epochs: 30
train_label_smoothing: 0.1
train_mixup_alpha: 0.4
train_precision_at_k: 3
train_seed: 42
train_use_mixup: true
