name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        continue-on-error: true  
        run: |
          black --check .
          isort --profile=black --check-only .
          flake8 .

      - name: Tests
        run: pytest -q

      - name: Quick train + eval
        run: |
          python scripts/run_pipeline.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts
          path: |
            checkpoints/
            results/
            mlruns/

      - name: Evaluate & log report
        run: |
          python evaluate_latest_run.py       

      - name: Render notebook
        run: |
          jupyter nbconvert --execute validation_report.ipynb --to notebook
