name: Photo-Tag self-hosted pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      max-samples:
        description: "Limit training samples"
        required: false
        default: "50"
      report:
        type: boolean
        description: "Generate evaluation report?"
        default: true

# ────────────────────────────
jobs:
  run-pipeline:
    runs-on:  # <- label filter
      - self-hosted             
      - windows                 
      - x64                     
      # - gpu                   
    defaults:
      run:
        shell: powershell
    # ─── Make src.* importable everywhere ────────────────
    env:
      PYTHONPATH: >
        ${{ github.workspace }};
        ${{ github.workspace }}\photo_tag_pipeline
    steps:
      # checkout source
      - uses: actions/checkout@v4

      # set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies **inside the real project root**
      - name: Install deps + project
        working-directory: photo_tag_pipeline
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .               # editable install adds src/ to PYTHONPATH

      # run your script, wiring workflow-dispatch inputs
      - name: Run pipeline
        working-directory: SmartPhotoMultiTag_pipeline 
        env:
          MAX_SAMPLES: ${{ github.event.inputs.max-samples || '50' }}
          REPORT:      ${{ github.event.inputs.report      || 'false' }}
        run: |
          $reportFlag = if ($env:REPORT -eq 'true') { '--report' } else { '' }

          python scripts/run_pipeline.py `
            --max-samples $env:MAX_SAMPLES `
            $reportFlag
