name: Photo-Tag pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      max-samples:
        description: Limit training samples
        default: "50"
      report:
        type: boolean
        description: Generate evaluation report?
        default: true
      image-size:
        description: Size of the images
        default: "100"
      batch-size:
        description: Batch size for training
        default: "32"
      num-workers:
        description: Number of workers for data loading
        default: "8"
      backbone:
        description: Model backbone
        default: "resnet18"
        type: choice
        options:
        - resnet18
        - resnet50
        - efficientnet_b0
      epochs:
        description: Number of training epochs
        default: "30"
      early-stop-patience:
        description: Patience for early stopping
        default: "7"

# ────────────────────────────
jobs:
  run-pipeline:
    runs-on:  # <- label filter
      - self-hosted             
      - Linux                 
      
    defaults:
      run:
        shell: bash

    steps:
      # checkout source
      - uses: actions/checkout@v4

      # set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # install deps (cache wheels for speed)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .  # install local src package

      # run your script, wiring workflow-dispatch inputs
      - name: Run pipeline
        run: |
          python scripts/run_pipeline.py \
            --max-samples "${{ github.event.inputs.max-samples || '50' }}" \
            --image-size "${{ github.event.inputs.image-size || '100' }}" \
            --batch-size "${{ github.event.inputs.batch-size || '32' }}" \
            --num-workers "${{ github.event.inputs.num-workers || '8' }}" \
            --backbone "${{ github.event.inputs.backbone || '50' }}" \
            --epochs $env:EPOCHS "${{ github.event.inputs.backbone || '50' }}" \
            --backbone "${{ github.event.inputs.backbone || '50' }}" \
            --early-stop-patience "${{ github.event.inputs.early-stop-patience || '7' }}" \
            $([[ "${{ github.event.inputs.report }}" == 'true' ]] && echo --report)

      # Upload training artifacts
      - name: Upload training artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: |
            checkpoints/
            results/
            mlruns/