name: Photo-Tag self-hosted pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      max-samples:
        description: "Limit training samples"
        required: false
        default: "50"
      report:
        type: boolean
        description: "Generate evaluation report?"
        default: true

# ────────────────────────────
jobs:
  run-pipeline:
    runs-on:  # <- label filter
      - self-hosted             
      - windows                 
      - x64                     
      # - gpu                   
    defaults:
      run:
        shell: powershell

    steps:
      # checkout source
      - uses: actions/checkout@v4

      # set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # install deps (cache wheels for speed)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # run your script, wiring workflow-dispatch inputs
      - name: Run pipeline
        env:
          MAX_SAMPLES: ${{ github.event.inputs.max-samples || '50' }}
          REPORT:      ${{ github.event.inputs.report      || 'false' }}
        run: |
          # PowerShell-native conditional for --report flag
          $reportFlag = if ($env:REPORT -eq 'true') { '--report' } else { '' }

          python scripts/run_pipeline.py `
            --max-samples $env:MAX_SAMPLES `
            $reportFlag
