name: Photo-Tag self-hosted pipeline

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      max-samples:
        description: Limit training samples
        default: "50"
      report:
        type: boolean
        description: Generate evaluation report?
        default: true

jobs:
  run-pipeline:
    runs-on:  # <- label filter
      - self-hosted             
      - windows                 
      - x64                     
      # - gpu                   
    defaults:
      run:
        shell: powershell

    steps:
      # Check out repository ⇒ $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install third-party deps + local package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .        # editable install registers src/

      # Run the pipeline
      - name: Run pipeline
        env:
          MAX_SAMPLES: ${{ github.event.inputs.max-samples || '50' }}
          REPORT:      ${{ github.event.inputs.report      || 'false' }}
        run: |
          $reportFlag = if ($env:REPORT -eq 'true') { '--report' } else { '' }

          python scripts/run_pipeline.py `
            --max-samples $env:MAX_SAMPLES `
            $reportFlag